# Generated by Django 4.2.7 on 2023-11-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание')),
                ('status', models.TextField(default='New', max_length=20, verbose_name='Статус')),
                ('date', models.DateField(default='', verbose_name='Дата')),
            ],
        ),
    ]
