# Generated by Django 4.2.7 on 2023-12-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_app', '0002_alter_todolist_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='detailed_desc',
            field=models.TextField(default='', max_length=2000, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
    ]
